### ISSUE TITLE
Blackbars

### ISSUE THREAD

**Issue by Djboy08** [Smotherer007/pMapTilesCutter#2]
![image](https://user-images.githubusercontent.com/34119605/204689664-98b37cfa-53ce-446f-89e1-43f78efb8ece.png)

I get these black bars when the size is fully divisible by 256,
The width is 4096, and the height is 3328

**Comment by Smotherer007** [comment]
Yes those bars are needed to keep the correct format for leaflet and google maps. If you like I will add a parameter to change the colors for those bars.

**Comment by Smotherer007** [comment]
Hi,

I have added now the colorization of those bars.

![image](https://user-images.githubusercontent.com/80619462/204750243-6e4d6579-3d63-40bf-aee8-fd3747f19677.png)

Kind regards

**Comment by Djboy08** [comment]
Thank you! Just to confirm too, the black bars you added correct? It won't be changing the aspect ratio of the map itself?

**Comment by Smotherer007** [comment]
Yes correct. You can change the color and the transparency of the aspect ratio bars, not of the given map it self. Just try it and you will see the result.
